# Generated by Django 2.2.19 on 2022-04-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220405_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
    ]
