# Generated by Django 2.2.19 on 2022-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20220406_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False, verbose_name=models.CharField(max_length=100)),
        ),
    ]
