# Generated by Django 2.2.19 on 2022-04-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
